version: "3"

services:
  opencloning:
    build: .
    container_name: opencloning
    # image: manulera/opencloning
    # For eLabFTW
    image: manulera/opencloning:prod-oc-base
    ports:
      - "8000:8000"

    volumes:
      #config.json maps in this directory maps to /frontend/config.json
      # use this for further configuration
      - ./config.json:/home/backend/frontend/config.json

    environment:
    # If you want to allow other origins via CORS (comma separated)
    # IMPORTANT: Do not add a trailing slash to the URLs:
    #   > Do not use http://localhost:3000/, but http://localhost:3000
      - ALLOWED_ORIGINS=http://localhost:3000
    # If you want to use a subpath of the domain, set ROOT_PATH,
    # this is the equivalent of --root-path in uvicorn, so the routes
    # without this prefix will also work (e.g. / will be the same as /opencloning/).
    # IMPORTANT: Do not add trailing slash, and don't use quotes.
      - ROOT_PATH=/opencloning
  nginx:
    image: nginx:latest
    ports:
      - "3000:3000"
    depends_on:
      - opencloning
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=3000
    volumes:
      - ./nginx_docker.config:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro

